---
Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: ./artifacts/crypto-config/ordererOrganizations/hurley.lab/msp

 
  - &org1
    Name: org1MSP
    ID: org1MSP
    MSPDir: ./artifacts/crypto-config/peerOrganizations/org1.hurley.lab/msp
    AnchorPeers:
      - Host: peer0.org1.hurley.lab
        Port: 7051
 
  - &org2
    Name: org2MSP
    ID: org2MSP
    MSPDir: ./artifacts/crypto-config/peerOrganizations/org2.hurley.lab/msp
    AnchorPeers:
      - Host: peer0.org2.hurley.lab
        Port: 7051


Orderer: &OrdererDefaults
  OrdererType: solo

  Addresses:
    - orderer.hurley.lab:7050

  BatchTimeout: 2s

  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB

  Organizations:

Application: &ApplicationDefaults
  Organizations:

Profiles:
  OrgsOrdererGenesis:
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
    Consortiums:
      SampleConsortium:
        Organizations:
          - *org1
          - *org2
          

  OrgsChannel:
    Consortium: SampleConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *org1
        - *org2
        
    